### ISSUE TITLE
Teaching Assignments

### ISSUE THREAD

**Issue by pdoehle** [OSU-Carpentry/2017-07-27-okstate#1]
Have instructors decide which topics they want and which internal workshops they want to teach at. Update names on website.

**Comment by pdoehle** [comment]
I've confirmed with Ross and Kevin. They will be team teaching Data Organization with Spreadsheets and OpenRefine. They are taking the July 14th internal workshop.

That leaves the following internal workshop dates open for Dave and Patrick:
* July 7th
* July 21st

Any preferences?
@tpboyle @djlampert @krdyke @r-bowman

**Comment by pdoehle** [comment]
Hi Instructors,

Based on what you have told me, I have the following teaching assignments/internal workshop dates:
| Date | Instructor | Topic |
| --- | --- | --- |
| June 30 | Phillip | SQL |
| July 7 |  Patrick | Data visualization with Python |
| July 14 | Ross and Kevin | Data Organization in Spreadsheets and OpenRefine |
| July 21 |Dave | Intro to Python |
| July 27-28 | Everybody | Full workshop |

@tpboyle @djlampert @krdyke @r-bowman

**Comment by djlampert** [comment]
Phillip—am I going on the 7th or the 21st?

Dave

**Comment by pdoehle** [comment]
Hi Dave,

My apologies, I put you on the wrong day. You are going on the 21st. You
may be out of town on the 7th, is that correct?

Phillip

**Comment by djlampert** [comment]
I think I will be out on the 7th, yes.

**Comment by pdoehle** [comment]
I have you down for the 21st now:
https://github.com/OSU-Carpentry/2017-07-27-okstate/issues/3.
