### ISSUE TITLE
reference links don't work

### ISSUE THREAD

**Issue by woodcmiami** [OSU-Carpentry/2017-07-27-okstate#7]
there reference link doesn't work

**Comment by pdoehle** [comment]
Are you talking about lesson content?

**Comment by woodcmiami** [comment]
ON this page under syllabus there are links called reference which go nowhere:
https://osu-carpentry.github.io/2017-07-27-okstate/

Chris Wood
chris<dot>wood<at>okstate<dot>edu

On Jul 10, 2017, at 12:19 PM, Phillip Doehle <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you talking about lesson content?

**Comment by pdoehle** [comment]
Hi Chris,

Thanks for bringing that to our attention. I have fixed the links. They should be working now.
